### ISSUE TITLE
Update output format description in magma/mf.m

### ISSUE THREAD

**Issue by JohnCremona** [JohnCremona/CMFs#119]
The detailed description of the output format from NewspaceData in lines 179-209 is not quite up to date.  Specifically I noticed that the entries in the E field are neither <g,b,n,m,e> nor <g,b,n,m,e,x>  but <g,b,n,D,e,x,m> where
 -  the 4th component D is the order's discriminant + factorization 
 - the 7th component m is the least m such that the first m entries of e generate the order as a ring

I'm only making this an issue rather than just editing it for confirmation by @AndrewVSutherland .

I am editing the sage functions in sage-pari/mf_compare.py to correctly read the output string from NewspaceData, which it used to do but needs a little tweaking now.

**Comment by AndrewVSutherland** [comment]
@JohnCremona Yes, the Readme.md file is correct and the documentation in the code is out of date (the code does what the Readme.md says), I just updated  the comments in the code via #120.

**Comment by JohnCremona** [comment]
Thanks -- I should have looked in the README, but this also shows that it's a bad idea to have parallel version of things like this.
